[package]
name = "synth-backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rodio = "0.17.2"
rand = "0.8.5"
rand_distr = "0.4.3"